### PR TITLE
use default popup

### LINKED ISSUE #657: Browser Extension: Vivaldi window keeps closing
**Describe the bug**
When I click the Fleeting Notes icon, the window opens and closes immediately 

**To Reproduce**
Steps to reproduce the behaviour:
1. Download browser ext on vivaldi on windows machine
2. Open Fleeting Notes app see that it immediately closes as I open the app in browser ext

### PR DESCRIPTION
**Pull request by matthewwong525**
Closes #657 
use default popup for fleeting notes & remove content injecting sidebar
image

### CODE REVIEW

File: web/extension/background.js [hunk 1]
```diff
@@ -124,6 +111,7 @@ const initCommands = () => {
 // popup.js
 const winIds = new Set();
 const openPopup = async (url, closeOnFocusChange = true) => {
+  console.log('open popup');
```
Comment (matthewwong525) [inline web/extension/background.js:114]:
```suggestion
```
